In [23]:
%load_ext autoreload
%autoreload 2

from dataraw_sampling import *
import itertools
import numpy as np
from collections import defaultdict, Counter
from tqdm import tqdm
import time
import random


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [25]:
query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=4, num_attr_vals=3, N=3)

In [28]:
query_props

[array([2, 0, 0, 2]),
 array([2, 2, 1, 2]),
 array([2, 0, 1, 2]),
 array([2, 3, 0, 2]),
 array([1, 0, 2, 2]),
 array([0, 0, 1, 1])]

In [33]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(100):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=4, num_attr_vals=3, N=3)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 99


In [87]:
Counter([len(sub) for sub in all_ans_subsets])

Counter({2: 3089,
         6: 5066,
         18: 820,
         10: 3711,
         4: 8003,
         12: 4305,
         11: 933,
         28: 615,
         5: 465,
         17: 229,
         15: 310,
         30: 616,
         29: 313,
         33: 313,
         3: 108,
         9: 54,
         1: 64,
         54: 12,
         36: 204,
         45: 52,
         27: 12,
         81: 1})

In [13]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []
for _ in range(1000000):
    # set, int
    ans_subset, ans_subset_size = draw_N_cardpairs(num_attributes=4, num_attr_vals=3, N=3)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 712807


In [14]:
Counter([len(sub) for sub in all_ans_subsets])

Counter({5: 98264,
         3: 25636,
         15: 51536,
         19: 19284,
         12: 25054,
         7: 119862,
         13: 98016,
         18: 12228,
         11: 42054,
         8: 13388,
         35: 3444,
         6: 15982,
         10: 3881,
         34: 4660,
         14: 28160,
         39: 3842,
         9: 47062,
         31: 11678,
         20: 12262,
         23: 1199,
         30: 5667,
         2: 992,
         29: 5411,
         32: 5256,
         33: 4800,
         36: 4162,
         16: 6427,
         21: 17076,
         24: 2172,
         26: 1209,
         17: 2888,
         37: 3643,
         25: 575,
         4: 6437,
         27: 1616,
         42: 1014,
         63: 57,
         49: 145,
         38: 1761,
         28: 648,
         57: 187,
         47: 616,
         48: 398,
         51: 376,
         46: 575,
         41: 570,
         55: 173,
         45: 386,
         54: 73,
         81: 1,
         1: 4})

In [ ]:
Counter([len(sub) for sub in all_ans_subsets])

In [12]:
start_time = time.time()

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []
for _ in tqdm(range(1024)):
    # set, int
    ans_subset, ans_subset_size = draw_N_cardpairs(num_attributes=4, num_attr_vals=3, N=3)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))
print('Time used to sample = ', time.time()-start_time)

100%|██████████| 1024/1024 [00:00<00:00, 3789.03it/s]

Number of card subsets generated = 1007
Time used to sample =  0.27445101737976074


In [10]:
start_time = time.time()

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []
for _ in tqdm(range(1024)):
    # set, int
    ans_subset, ans_subset_size = draw_N_cardpairs(num_attributes=5, num_attr_vals=3, N=3)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))
print('Time used to sample = ', time.time()-start_time)

100%|██████████| 1024/1024 [00:00<00:00, 3963.20it/s]

Number of card subsets generated = 1022
Time used to sample =  0.41678452491760254


In [44]:
# time rejection sampling

num_attributes=4; num_attr_vals=3

start_time = time.time()

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

fails = 0

for _ in tqdm(range(1024)):
    success = False
    while not success:
        query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes, num_attr_vals, N=3)
        if random.random() <= (len(ans_subset) *1.0 / (num_attr_vals**num_attributes)):
            success = True
        else:
            fails += 1
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))
print('Time used to sample = ', time.time()-start_time)

100%|██████████| 1024/1024 [00:01<00:00, 821.77it/s]

Number of card subsets generated = 957
Time used to sample =  1.253709077835083


In [52]:
ans_len

9

In [46]:
Counter([len(sub) for sub in all_ans_subsets])

Counter({36: 24,
         19: 36,
         15: 73,
         54: 3,
         21: 30,
         12: 45,
         13: 103,
         46: 2,
         7: 67,
         30: 47,
         14: 42,
         11: 58,
         33: 32,
         29: 28,
         63: 1,
         23: 5,
         18: 29,
         9: 45,
         28: 36,
         39: 13,
         35: 10,
         20: 20,
         5: 50,
         6: 13,
         57: 1,
         32: 17,
         16: 9,
         38: 8,
         10: 8,
         37: 17,
         27: 15,
         47: 2,
         34: 9,
         31: 27,
         42: 4,
         3: 5,
         45: 4,
         4: 2,
         49: 1,
         8: 8,
         41: 1,
         17: 3,
         2: 1,
         81: 1,
         26: 1,
         24: 1})

In [67]:
# 4-3 N=2
np.log2(30751)

14.908345706150365

In [70]:
# 4-3 N=3
np.log2(711713)

19.440936062609453

In [64]:
sum(all_ans_subsets_count.values())

100000

In [65]:
756 / 100000

0.00756

In [63]:
# Debug, how come there are so many ones???
# Doesn't look right!

Counter(all_ans_subsets_count.values())

Counter({3: 6903,
         6: 1596,
         4: 5216,
         5: 3146,
         1: 4372,
         9: 93,
         2: 6775,
         12: 10,
         7: 703,
         11: 28,
         8: 322,
         53: 3,
         172: 1,
         57: 2,
         14: 10,
         10: 33,
         39: 2,
         197: 1,
         61: 1,
         15: 10,
         756: 1,
         177: 1,
         47: 4,
         44: 2,
         46: 3,
         54: 2,
         42: 4,
         222: 1,
         38: 1,
         194: 1,
         174: 2,
         17: 1,
         192: 2,
         56: 3,
         50: 3,
         13: 12,
         180: 1,
         43: 3,
         200: 1,
         62: 1,
         48: 1,
         49: 3,
         40: 2,
         51: 2,
         16: 4,
         45: 3,
         37: 2,
         41: 2,
         206: 1,
         30: 1,
         63: 1,
         52: 1,
         33: 1,
         31: 1,
         18: 1})

In [ ]:
# 2 - 3

# If we concat four paris, how many unique subsets do we cover? 
# Length distribution?
# How long are the vectors?
# What does the matrix look like?

In [30]:
81**6

531441

In [31]:
1663740

1663740