In [3]:
%load_ext autoreload
%autoreload 2

from dataraw_sampling import *
import itertools
import numpy as np
from collections import defaultdict, Counter
from tqdm import tqdm
import time
import random


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=np.random.choice([1,2,4,8]))
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 248876


In [13]:
# ('|', '&', '!')

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=3)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 44601


In [9]:
# ('|', '&', '-', '!')

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=3)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 44080


In [ ]:
# TODO extend card2idx_lookup

In [5]:
query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=3)

In [6]:
query_props

[array([2, 1, 0]),
 array([2, 0, 0]),
 '&',
 array([0, 0, 0]),
 array([3, 3, 2]),
 '!',
 array([2, 2, 0]),
 array([2, 3, 0]),
 '-']

In [7]:
ans_subset

{(0, 0, 1),
 (0, 1, 1),
 (0, 2, 1),
 (1, 0, 1),
 (1, 1, 1),
 (1, 2, 1),
 (2, 0, 1),
 (2, 1, 1),
 (2, 2, 1)}

In [10]:
Counter([len(sub) for sub in all_ans_subsets])

Counter({12: 2275,
         8: 1690,
         23: 694,
         14: 1327,
         13: 3357,
         7: 7079,
         11: 4448,
         9: 3342,
         5: 9250,
         2: 351,
         6: 2394,
         3: 2923,
         25: 342,
         10: 1148,
         18: 272,
         21: 266,
         4: 1005,
         19: 99,
         22: 70,
         16: 579,
         15: 528,
         17: 558,
         26: 27,
         1: 27,
         24: 27,
         0: 1,
         27: 1})

In [18]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=3)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 28666


In [19]:
Counter([len(sub) for sub in all_ans_subsets])

Counter({13: 1944,
         7: 5697,
         5: 7371,
         2: 351,
         14: 810,
         6: 2052,
         12: 1404,
         11: 1377,
         9: 1269,
         3: 2925,
         8: 1296,
         18: 117,
         19: 108,
         10: 162,
         15: 405,
         4: 648,
         17: 324,
         16: 324,
         1: 27,
         21: 54,
         27: 1})

In [20]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=4)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 227045


In [22]:
Counter([len(sub) for sub in all_ans_subsets]).most_common()

[(8, 44131),
 (6, 40416),
 (9, 19595),
 (10, 19526),
 (7, 19350),
 (4, 13510),
 (14, 12766),
 (15, 9038),
 (13, 8640),
 (12, 8170),
 (5, 7355),
 (11, 6565),
 (16, 5857),
 (17, 2896),
 (18, 2762),
 (3, 2580),
 (19, 1923),
 (20, 999),
 (21, 335),
 (22, 324),
 (2, 198),
 (23, 79),
 (24, 27),
 (1, 2),
 (27, 1)]

In [23]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=5)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 392108


In [24]:
Counter([len(sub) for sub in all_ans_subsets]).most_common()

[(9, 56793),
 (8, 46731),
 (7, 42273),
 (10, 42193),
 (11, 36015),
 (6, 23827),
 (12, 22168),
 (15, 19857),
 (14, 19143),
 (13, 18867),
 (16, 16592),
 (5, 12975),
 (17, 11879),
 (18, 6997),
 (19, 4723),
 (4, 3946),
 (20, 3344),
 (21, 1793),
 (22, 788),
 (23, 522),
 (3, 376),
 (24, 218),
 (25, 79),
 (2, 8),
 (27, 1)]

In [25]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=6)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 470734


In [26]:
Counter([len(sub) for sub in all_ans_subsets]).most_common()

[(10, 56577),
 (11, 52489),
 (9, 50687),
 (12, 43752),
 (8, 38171),
 (13, 34302),
 (15, 31045),
 (14, 30984),
 (16, 29001),
 (17, 24142),
 (7, 22466),
 (18, 16090),
 (19, 10634),
 (6, 10505),
 (20, 7670),
 (21, 4558),
 (5, 3111),
 (22, 2255),
 (23, 1240),
 (4, 456),
 (24, 436),
 (25, 108),
 (26, 26),
 (3, 26),
 (2, 2),
 (27, 1)]

In [30]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=7)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 496104


In [31]:
Counter([len(sub) for sub in all_ans_subsets]).most_common()

[(12, 52615),
 (11, 52245),
 (13, 47897),
 (10, 44313),
 (14, 43696),
 (15, 42331),
 (16, 40047),
 (17, 36188),
 (9, 31763),
 (18, 27369),
 (19, 19008),
 (8, 18211),
 (20, 13256),
 (21, 8572),
 (7, 7923),
 (22, 4518),
 (6, 2544),
 (23, 2121),
 (24, 736),
 (5, 467),
 (25, 204),
 (4, 50),
 (26, 27),
 (3, 2),
 (27, 1)]

In [ ]:
# Watch here!

In [4]:
# ('|', '!')

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 861534


In [2]:
# ('|', '&')

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 79284


In [2]:
# ('|', '&')

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 79284


In [14]:
# ('|', '&', '!')

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 228596


In [11]:
# ('|', '&', '-', '!')

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 227285


In [30]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 496104


In [6]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(10_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=np.random.choice([1,2,4,8]))
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 1194854


In [7]:
# ('|', '!')

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(10_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=np.random.choice([1,2,4,8]))
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 2320745


In [12]:
query_props

[array([1, 1, 2]),
 array([2, 2, 2]),
 '!',
 array([2, 1, 0]),
 array([3, 3, 1]),
 '|',
 array([2, 2, 2]),
 array([0, 3, 2]),
 '!',
 array([2, 2, 1]),
 array([3, 2, 3]),
 '!',
 array([2, 2, 0]),
 array([3, 3, 0]),
 '|',
 array([0, 1, 2]),
 array([0, 3, 3]),
 '!',
 array([1, 0, 2]),
 array([2, 0, 0]),
 '|',
 array([2, 0, 0]),
 array([3, 1, 1]),
 '|']

In [11]:
# WATCH

# ('|', '!')

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(10_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_intersect_symdiff(num_attributes=3, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 6631494


In [8]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(10_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_only(num_attributes=3, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 2767275


In [10]:
# 3-3-8
Counter([len(sub) for sub in all_ans_subsets]).most_common()

[(13, 351555),
 (12, 345885),
 (14, 316880),
 (11, 293208),
 (15, 264520),
 (16, 217267),
 (10, 210586),
 (17, 179124),
 (18, 145235),
 (9, 124366),
 (19, 105947),
 (20, 66200),
 (8, 57279),
 (21, 37293),
 (7, 19854),
 (22, 17857),
 (23, 7022),
 (6, 4324),
 (24, 1921),
 (5, 534),
 (25, 351),
 (4, 38),
 (26, 27),
 (27, 1),
 (3, 1)]

In [40]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(10_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs_union_only(num_attributes=3, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 2766272


In [32]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=9)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 472752


In [41]:
1_000_000

1000000

In [34]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=10)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 440025


In [28]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=3, num_attr_vals=3, N=16)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 187036


In [29]:
Counter([len(sub) for sub in all_ans_subsets]).most_common()

[(20, 37190),
 (21, 35775),
 (19, 30766),
 (22, 24904),
 (18, 21298),
 (17, 12336),
 (23, 11139),
 (16, 6309),
 (24, 2781),
 (15, 2720),
 (14, 1019),
 (25, 351),
 (13, 310),
 (12, 91),
 (26, 27),
 (11, 18),
 (10, 1),
 (27, 1)]

In [35]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=4, num_attr_vals=3, N=4)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 919428


In [7]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(10_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=4, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 9577312


In [8]:
Counter([len(sub) for sub in all_ans_subsets]).most_common()

[(23, 383103),
 (24, 381303),
 (22, 379868),
 (26, 379341),
 (25, 378722),
 (27, 368429),
 (21, 360167),
 (28, 349287),
 (20, 327512),
 (29, 321342),
 (30, 290832),
 (19, 277798),
 (31, 267940),
 (32, 252145),
 (33, 241928),
 (18, 241609),
 (34, 236656),
 (35, 227948),
 (36, 221678),
 (37, 220236),
 (38, 218520),
 (40, 218470),
 (39, 217851),
 (41, 210423),
 (42, 203111),
 (17, 197120),
 (43, 192857),
 (16, 177872),
 (44, 173861),
 (45, 157387),
 (15, 140340),
 (46, 138927),
 (47, 122927),
 (14, 119319),
 (48, 111934),
 (49, 99410),
 (50, 86529),
 (13, 80089),
 (51, 73075),
 (52, 65113),
 (53, 56959),
 (12, 55125),
 (54, 47815),
 (55, 42160),
 (56, 35250),
 (57, 30631),
 (58, 28741),
 (11, 28278),
 (59, 25070),
 (60, 20040),
 (61, 17364),
 (10, 14510),
 (62, 11165),
 (63, 9201),
 (64, 6923),
 (65, 6283),
 (66, 5549),
 (9, 5366),
 (67, 5244),
 (68, 3232),
 (69, 2432),
 (8, 1737),
 (70, 1578),
 (71, 1215),
 (72, 731),
 (73, 646),
 (7, 396),
 (75, 260),
 (74, 230),
 (76, 110),
 (77, 30),


In [39]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=4, num_attr_vals=3, N=10)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

KeyboardInterrupt: 

In [37]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=4, num_attr_vals=3, N=12)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

Number of card subsets generated = 952831


In [ ]:
all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []

for _ in range(1_000_000):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=9, num_attr_vals=3, N=8)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

In [13]:
Counter([len(sub) for sub in all_ans_subsets])

Counter()

In [12]:
start_time = time.time()

all_ans_subsets = set()
all_ans_subsets_count = defaultdict(int)
ans_subset_sizes = []
for _ in tqdm(range(1024)):
    # set, int
    query_props, ans_subset, ans_len = draw_N_cardpairs(num_attributes=4, num_attr_vals=3, N=3)
    ans_subset = tuple(sorted(ans_subset))
    all_ans_subsets.add(ans_subset)
    all_ans_subsets_count[ans_subset] += 1
    
print('Number of card subsets generated =', len(all_ans_subsets))

100%|██████████| 1024/1024 [00:00<00:00, 3789.03it/s]

Number of card subsets generated = 1007
Time used to sample =  0.27445101737976074


In [ ]:
3**8